[project]
name = "dynamic-routing-web"
version = "0"
dependencies = [
    "fastapi", "uvicorn"
]

[dependency-groups]
dev = [
    "pytest",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


